// 7 verbatim rows from UI-Reference/discovery.md, plus the rest of the ~42-niche list built
// from templateCatalog.js's categories + the professional-services niches discovery.md names
// but doesn't give sample rows for (NDIS Providers, Childcare, Tutors, Coaches, Consultants,
// Real Estate Agents, Mortgage Brokers, Accountants) — those, and every non-verbatim row's
// difficulty/angle/avgValue, are reasoned in-house in the same style as the 7 verbatim rows,
// not sourced from a rubric that doesn't specify them.
export const DISCOVERY_NICHES = [
  { niche: 'Plumbing', difficulty: 'Easy', angle: '$0 upfront + monthly plan', avgValue: 250 },
  { niche: 'Roofing', difficulty: 'Medium', angle: 'Lead-gen landing page', avgValue: 400 },
  { niche: 'HVAC', difficulty: 'Easy', angle: 'Emergency call site', avgValue: 300 },
  { niche: 'Solar', difficulty: 'Hard', angle: 'Savings calculator funnel', avgValue: 500 },
  { niche: 'Dentists', difficulty: 'Hard', angle: 'New patient funnel', avgValue: 600 },
  { niche: 'Med Spas', difficulty: 'Hard', angle: 'Luxury brand site', avgValue: 700 },
  { niche: 'Lawyers', difficulty: 'Hard', angle: 'Practice-area authority', avgValue: 600 },
  { niche: 'Electricians', difficulty: 'Easy', angle: 'Same-day callout site', avgValue: 280 },
  { niche: 'Builders / Construction', difficulty: 'Medium', angle: 'Portfolio + quote funnel', avgValue: 450 },
  { niche: 'Bathroom Renovators', difficulty: 'Medium', angle: 'Before/after gallery site', avgValue: 500 },
  { niche: 'Kitchen Renovators', difficulty: 'Medium', angle: 'Before/after gallery site', avgValue: 550 },
  { niche: 'Painters', difficulty: 'Easy', angle: 'Instant quote form', avgValue: 250 },
  { niche: 'Landscapers', difficulty: 'Easy', angle: 'Seasonal offer site', avgValue: 300 },
  { niche: 'Fencing', difficulty: 'Easy', angle: 'Free measure & quote', avgValue: 280 },
  { niche: 'Pest Control', difficulty: 'Easy', angle: 'Recurring plan upsell', avgValue: 220 },
  { niche: 'Locksmiths', difficulty: 'Easy', angle: '24/7 emergency page', avgValue: 220 },
  { niche: 'Garage Door Repair', difficulty: 'Easy', angle: 'Same-day repair site', avgValue: 260 },
  { niche: 'Pressure Washing', difficulty: 'Easy', angle: 'Seasonal booking funnel', avgValue: 200 },
  { niche: 'Gutter Cleaning', difficulty: 'Easy', angle: 'Seasonal booking funnel', avgValue: 200 },
  { niche: 'Removalists', difficulty: 'Medium', angle: 'Instant moving quote', avgValue: 350 },
  { niche: 'Tree Removal', difficulty: 'Medium', angle: 'Emergency + quote funnel', avgValue: 400 },
  { niche: 'Pool Cleaners', difficulty: 'Easy', angle: 'Recurring plan upsell', avgValue: 220 },
  { niche: 'Smash Repair', difficulty: 'Medium', angle: 'Insurance-claim funnel', avgValue: 450 },
  { niche: 'Mechanics', difficulty: 'Easy', angle: 'Booking + quote site', avgValue: 250 },
  { niche: 'Physiotherapists', difficulty: 'Medium', angle: 'New patient funnel', avgValue: 450 },
  { niche: 'Chiropractors', difficulty: 'Medium', angle: 'New patient funnel', avgValue: 450 },
  { niche: 'Veterinarians', difficulty: 'Medium', angle: 'New client funnel', avgValue: 450 },
  { niche: 'Gyms', difficulty: 'Hard', angle: 'Membership signup funnel', avgValue: 500 },
  { niche: 'Personal Trainers', difficulty: 'Medium', angle: 'Free trial funnel', avgValue: 350 },
  { niche: 'Massage Clinics', difficulty: 'Easy', angle: 'Online booking site', avgValue: 280 },
  { niche: 'Hair Salons', difficulty: 'Easy', angle: 'Online booking site', avgValue: 250 },
  { niche: 'Barbers', difficulty: 'Easy', angle: 'Online booking site', avgValue: 220 },
  { niche: 'Beauty Salons', difficulty: 'Medium', angle: 'Service-menu booking site', avgValue: 320 },
  { niche: 'Nail Salons', difficulty: 'Easy', angle: 'Online booking site', avgValue: 220 },
  { niche: 'Cafes', difficulty: 'Easy', angle: 'Menu + location site', avgValue: 200 },
  { niche: 'Restaurants', difficulty: 'Medium', angle: 'Booking + menu site', avgValue: 350 },
  { niche: 'Catering Companies', difficulty: 'Medium', angle: 'Event-quote funnel', avgValue: 450 },
  { niche: 'NDIS Providers', difficulty: 'Hard', angle: 'Trust-building intake funnel', avgValue: 650 },
  { niche: 'Childcare', difficulty: 'Hard', angle: 'Enrolment waitlist funnel', avgValue: 600 },
  { niche: 'Tutors', difficulty: 'Easy', angle: 'Free trial lesson funnel', avgValue: 250 },
  { niche: 'Coaches', difficulty: 'Medium', angle: 'Discovery-call booking funnel', avgValue: 400 },
  { niche: 'Consultants', difficulty: 'Hard', angle: 'Authority + booking funnel', avgValue: 600 },
  { niche: 'Real Estate Agents', difficulty: 'Hard', angle: 'Listing + lead-capture site', avgValue: 700 },
  { niche: 'Mortgage Brokers', difficulty: 'Hard', angle: 'Pre-approval funnel', avgValue: 650 },
  { niche: 'Accountants', difficulty: 'Medium', angle: 'Free-consult booking site', avgValue: 450 },
]
